/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gest.lt (https://sketchfab.com/gestLT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electric-scooter-f3785071e9244d83ba311b7da48a1085
Title: Electric Scooter
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three'
import { useFrame } from '@react-three/fiber'
import ScooterScene from '../models/electric_scooter.glb'


const ScooterModel = (props) => {

  const ScooterRef = useRef()
  const { nodes, materials } = useGLTF(ScooterScene)

  useFrame(({ clock }) => {
    // Calculate rotation angle based on time
    const angle = Math.sin(clock.getElapsedTime()) * 1; // Adjust the rotation speed by changing the multiplier
    ScooterRef.current.rotation.y = angle; // Rotate the model around the y-axis 
  });

  
  return (
    <a.group ref={ScooterRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.036}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ElectricScooter_ElectricScooter_0.geometry}
            material={materials.ElectricScooter}
            position={[-2.003, 0, 0.761]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </a.group>
  )
}

export default ScooterModel

